# Generated by Django 4.2.5 on 2023-12-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_qol_delete_age1df_delete_age2df_delete_age3df_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qol',
            options={},
        ),
    ]
