# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Soc1994(models.Model):
    year = models.IntegerField(db_column='YEAR', blank=True, null=True)  # Field name made lowercase.
    commid = models.IntegerField(db_column='CommID', blank=True, primary_key=True)  # Field name made lowercase.
    fipspl = models.IntegerField(db_column='FIPSPL', blank=True, null=True)  # Field name made lowercase.
    name = models.TextField(db_column='NAME', blank=True, null=True)  # Field name made lowercase.
    cat = models.TextField(db_column='CAT', blank=True, null=True)  # Field name made lowercase.
    scfriends_none = models.FloatField(db_column='SCfriends_none', blank=True, null=True)  # Field name made lowercase.
    scfriends_vfew = models.FloatField(db_column='SCfriends_vfew', blank=True, null=True)  # Field name made lowercase.
    scfriends_some = models.FloatField(db_column='SCfriends_some', blank=True, null=True)  # Field name made lowercase.
    scfriends_half = models.FloatField(db_column='SCfriends_half', blank=True, null=True)  # Field name made lowercase.
    scfriends_most = models.FloatField(db_column='SCfriends_most', blank=True, null=True)  # Field name made lowercase.
    scfriends_all = models.FloatField(db_column='SCfriends_all', blank=True, null=True)  # Field name made lowercase.
    screlatives_none = models.FloatField(db_column='SCrelatives_none', blank=True, null=True)  # Field name made lowercase.
    screlatives_vfew = models.FloatField(db_column='SCrelatives_vfew', blank=True, null=True)  # Field name made lowercase.
    screlatives_some = models.FloatField(db_column='SCrelatives_some', blank=True, null=True)  # Field name made lowercase.
    screlatives_half = models.FloatField(db_column='SCrelatives_half', blank=True, null=True)  # Field name made lowercase.
    screlatives_most = models.FloatField(db_column='SCrelatives_most', blank=True, null=True)  # Field name made lowercase.
    screlatives_all = models.FloatField(db_column='SCrelatives_all', blank=True, null=True)  # Field name made lowercase.
    scsupportive_vsa = models.FloatField(db_column='SCsupportive_vsa', blank=True, null=True)  # Field name made lowercase.
    scsupportive_sa = models.FloatField(db_column='SCsupportive_sa', blank=True, null=True)  # Field name made lowercase.
    scsupportive_a = models.FloatField(db_column='SCsupportive_a', blank=True, null=True)  # Field name made lowercase.
    scsupportive_n = models.FloatField(db_column='SCsupportive_n', blank=True, null=True)  # Field name made lowercase.
    scsupportive_d = models.FloatField(db_column='SCsupportive_d', blank=True, null=True)  # Field name made lowercase.
    scsupportive_sd = models.FloatField(db_column='SCsupportive_sd', blank=True, null=True)  # Field name made lowercase.
    scsupportive_vsd = models.FloatField(db_column='SCsupportive_vsd', blank=True, null=True)  # Field name made lowercase.
    scorgsworkall_sa = models.FloatField(db_column='SCorgsworkall_sa', blank=True, null=True)  # Field name made lowercase.
    scorgsworkall_a = models.FloatField(db_column='SCorgsworkall_a', blank=True, null=True)  # Field name made lowercase.
    scorgsworkall_n = models.FloatField(db_column='SCorgsworkall_n', blank=True, null=True)  # Field name made lowercase.
    scorgsworkall_d = models.FloatField(db_column='SCorgsworkall_d', blank=True, null=True)  # Field name made lowercase.
    scorgsworkall_sd = models.FloatField(db_column='SCorgsworkall_sd', blank=True, null=True)  # Field name made lowercase.
    scnewresleader_sa = models.FloatField(db_column='SCnewresleader_sa', blank=True, null=True)  # Field name made lowercase.
    scnewresleader_a = models.FloatField(db_column='SCnewresleader_a', blank=True, null=True)  # Field name made lowercase.
    scnewresleader_n = models.FloatField(db_column='SCnewresleader_n', blank=True, null=True)  # Field name made lowercase.
    scnewresleader_d = models.FloatField(db_column='SCnewresleader_d', blank=True, null=True)  # Field name made lowercase.
    scnewresleader_sd = models.FloatField(db_column='SCnewresleader_sd', blank=True, null=True)  # Field name made lowercase.
    scopenideas_vsa = models.FloatField(db_column='SCopenideas_vsa', blank=True, null=True)  # Field name made lowercase.
    scopenideas_sa = models.FloatField(db_column='SCopenideas_sa', blank=True, null=True)  # Field name made lowercase.
    scopenideas_a = models.FloatField(db_column='SCopenideas_a', blank=True, null=True)  # Field name made lowercase.
    scopenideas_n = models.FloatField(db_column='SCopenideas_n', blank=True, null=True)  # Field name made lowercase.
    scopenideas_d = models.FloatField(db_column='SCopenideas_d', blank=True, null=True)  # Field name made lowercase.
    scopenideas_sd = models.FloatField(db_column='SCopenideas_sd', blank=True, null=True)  # Field name made lowercase.
    scopenideas_vsd = models.FloatField(db_column='SCopenideas_vsd', blank=True, null=True)  # Field name made lowercase.
    sclocalorg_none = models.FloatField(db_column='SClocalorg_none', blank=True, null=True)  # Field name made lowercase.
    sclocalorg_1plus = models.FloatField(db_column='SClocalorg_1plus', blank=True, null=True)  # Field name made lowercase.
    sclocalorg_2plus = models.FloatField(db_column='SClocalorg_2plus', blank=True, null=True)  # Field name made lowercase.
    sclocalorg_3plus = models.FloatField(db_column='SClocalorg_3plus', blank=True, null=True)  # Field name made lowercase.
    sclocalorg_4plus = models.FloatField(db_column='SClocalorg_4plus', blank=True, null=True)  # Field name made lowercase.
    scoutsideorg_none = models.FloatField(db_column='SCoutsideorg_none', blank=True, null=True)  # Field name made lowercase.
    scoutsideorg_1plus = models.FloatField(db_column='SCoutsideorg_1plus', blank=True, null=True)  # Field name made lowercase.
    scoutsideorg_2plus = models.FloatField(db_column='SCoutsideorg_2plus', blank=True, null=True)  # Field name made lowercase.
    scoutsideorg_3plus = models.FloatField(db_column='SCoutsideorg_3plus', blank=True, null=True)  # Field name made lowercase.
    scoutsideorg_4plus = models.FloatField(db_column='SCoutsideorg_4plus', blank=True, null=True)  # Field name made lowercase.
    scactiveorg_not = models.FloatField(db_column='SCactiveorg_not', blank=True, null=True)  # Field name made lowercase.
    scactiveorg_little = models.FloatField(db_column='SCactiveorg_little', blank=True, null=True)  # Field name made lowercase.
    scactiveorg_some = models.FloatField(db_column='SCactiveorg_some', blank=True, null=True)  # Field name made lowercase.
    scactiveorg_very = models.FloatField(db_column='SCactiveorg_very', blank=True, null=True)  # Field name made lowercase.
    sclocoutorg_local = models.FloatField(db_column='SClocoutorg_local', blank=True, null=True)  # Field name made lowercase.
    sclocoutorg_outside = models.FloatField(db_column='SClocoutorg_outside', blank=True, null=True)  # Field name made lowercase.
    sclocoutorg_both = models.FloatField(db_column='SClocoutorg_both', blank=True, null=True)  # Field name made lowercase.
    sclocoutorg_none = models.FloatField(db_column='SClocoutorg_none', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_none = models.FloatField(db_column='CEvolunteer_none', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_1plus = models.FloatField(db_column='CEvolunteer_1plus', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_1 = models.FloatField(db_column='CEvolunteer_1', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_2 = models.FloatField(db_column='CEvolunteer_2', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_3to4 = models.FloatField(db_column='CEvolunteer_3to4', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_5to9 = models.FloatField(db_column='CEvolunteer_5to9', blank=True, null=True)  # Field name made lowercase.
    cevolunteer_10plus = models.FloatField(db_column='CEvolunteer_10plus', blank=True, null=True)  # Field name made lowercase.
    cetowngetsbehind_sa = models.FloatField(db_column='CEtowngetsbehind_sa', blank=True, null=True)  # Field name made lowercase.
    cetowngetsbehind_a = models.FloatField(db_column='CEtowngetsbehind_a', blank=True, null=True)  # Field name made lowercase.
    cetowngetsbehind_n = models.FloatField(db_column='CEtowngetsbehind_n', blank=True, null=True)  # Field name made lowercase.
    cetowngetsbehind_d = models.FloatField(db_column='CEtowngetsbehind_d', blank=True, null=True)  # Field name made lowercase.
    cetowngetsbehind_sd = models.FloatField(db_column='CEtowngetsbehind_sd', blank=True, null=True)  # Field name made lowercase.
    ceinvolvdecisions_sa = models.FloatField(db_column='CEinvolvdecisions_sa', blank=True, null=True)  # Field name made lowercase.
    ceinvolvdecisions_a = models.FloatField(db_column='CEinvolvdecisions_a', blank=True, null=True)  # Field name made lowercase.
    ceinvolvdecisions_n = models.FloatField(db_column='CEinvolvdecisions_n', blank=True, null=True)  # Field name made lowercase.
    ceinvolvdecisions_d = models.FloatField(db_column='CEinvolvdecisions_d', blank=True, null=True)  # Field name made lowercase.
    ceinvolvdecisions_sd = models.FloatField(db_column='CEinvolvdecisions_sd', blank=True, null=True)  # Field name made lowercase.
    casorryleave_sa = models.FloatField(db_column='CAsorryleave_sa', blank=True, null=True)  # Field name made lowercase.
    casorryleave_a = models.FloatField(db_column='CAsorryleave_a', blank=True, null=True)  # Field name made lowercase.
    casorryleave_n = models.FloatField(db_column='CAsorryleave_n', blank=True, null=True)  # Field name made lowercase.
    casorryleave_d = models.FloatField(db_column='CAsorryleave_d', blank=True, null=True)  # Field name made lowercase.
    casorryleave_sd = models.FloatField(db_column='CAsorryleave_sd', blank=True, null=True)  # Field name made lowercase.
    cafeelhome_sa = models.FloatField(db_column='CAfeelhome_sa', blank=True, null=True)  # Field name made lowercase.
    cafeelhome_a = models.FloatField(db_column='CAfeelhome_a', blank=True, null=True)  # Field name made lowercase.
    cafeelhome_n = models.FloatField(db_column='CAfeelhome_n', blank=True, null=True)  # Field name made lowercase.
    cafeelhome_d = models.FloatField(db_column='CAfeelhome_d', blank=True, null=True)  # Field name made lowercase.
    cafeelhome_sd = models.FloatField(db_column='CAfeelhome_sd', blank=True, null=True)  # Field name made lowercase.
    catownlikefriends_sa = models.FloatField(db_column='CAtownlikefriends_sa', blank=True, null=True)  # Field name made lowercase.
    catownlikefriends_a = models.FloatField(db_column='CAtownlikefriends_a', blank=True, null=True)  # Field name made lowercase.
    catownlikefriends_n = models.FloatField(db_column='CAtownlikefriends_n', blank=True, null=True)  # Field name made lowercase.
    catownlikefriends_d = models.FloatField(db_column='CAtownlikefriends_d', blank=True, null=True)  # Field name made lowercase.
    catownlikefriends_sd = models.FloatField(db_column='CAtownlikefriends_sd', blank=True, null=True)  # Field name made lowercase.
    csmoregoforit_sa = models.FloatField(db_column='CSmoregoforit_sa', blank=True, null=True)  # Field name made lowercase.
    csmoregoforit_a = models.FloatField(db_column='CSmoregoforit_a', blank=True, null=True)  # Field name made lowercase.
    csmoregoforit_n = models.FloatField(db_column='CSmoregoforit_n', blank=True, null=True)  # Field name made lowercase.
    csmoregoforit_d = models.FloatField(db_column='CSmoregoforit_d', blank=True, null=True)  # Field name made lowercase.
    csmoregoforit_sd = models.FloatField(db_column='CSmoregoforit_sd', blank=True, null=True)  # Field name made lowercase.
    cswellkept_vsa = models.FloatField(db_column='CSwellkept_vsa', blank=True, null=True)  # Field name made lowercase.
    cswellkept_sa = models.FloatField(db_column='CSwellkept_sa', blank=True, null=True)  # Field name made lowercase.
    cswellkept_a = models.FloatField(db_column='CSwellkept_a', blank=True, null=True)  # Field name made lowercase.
    cswellkept_n = models.FloatField(db_column='CSwellkept_n', blank=True, null=True)  # Field name made lowercase.
    cswellkept_d = models.FloatField(db_column='CSwellkept_d', blank=True, null=True)  # Field name made lowercase.
    cswellkept_sd = models.FloatField(db_column='CSwellkept_sd', blank=True, null=True)  # Field name made lowercase.
    cswellkept_vsd = models.FloatField(db_column='CSwellkept_vsd', blank=True, null=True)  # Field name made lowercase.
    cslookoutforself_sa = models.FloatField(db_column='CSlookoutforself_sa', blank=True, null=True)  # Field name made lowercase.
    cslookoutforself_a = models.FloatField(db_column='CSlookoutforself_a', blank=True, null=True)  # Field name made lowercase.
    cslookoutforself_n = models.FloatField(db_column='CSlookoutforself_n', blank=True, null=True)  # Field name made lowercase.
    cslookoutforself_d = models.FloatField(db_column='CSlookoutforself_d', blank=True, null=True)  # Field name made lowercase.
    cslookoutforself_sd = models.FloatField(db_column='CSlookoutforself_sd', blank=True, null=True)  # Field name made lowercase.
    goservprimhealth_local = models.FloatField(db_column='GOSERVprimhealth_local', blank=True, null=True)  # Field name made lowercase.
    goservprimhealth_outside = models.FloatField(db_column='GOSERVprimhealth_outside', blank=True, null=True)  # Field name made lowercase.
    goservprimhealth_dnu = models.FloatField(db_column='GOSERVprimhealth_dnu', blank=True, null=True)  # Field name made lowercase.
    goservspechealth_local = models.FloatField(db_column='GOSERVspechealth_local', blank=True, null=True)  # Field name made lowercase.
    goservspechealth_outside = models.FloatField(db_column='GOSERVspechealth_outside', blank=True, null=True)  # Field name made lowercase.
    goservspechealth_dnu = models.FloatField(db_column='GOSERVspechealth_dnu', blank=True, null=True)  # Field name made lowercase.
    goservshopdaily_local = models.FloatField(db_column='GOSERVshopdaily_local', blank=True, null=True)  # Field name made lowercase.
    goservshopdaily_outside = models.FloatField(db_column='GOSERVshopdaily_outside', blank=True, null=True)  # Field name made lowercase.
    goservshopdaily_dnu = models.FloatField(db_column='GOSERVshopdaily_dnu', blank=True, null=True)  # Field name made lowercase.
    goservshopbig_local = models.FloatField(db_column='GOSERVshopbig_local', blank=True, null=True)  # Field name made lowercase.
    goservshopbig_outside = models.FloatField(db_column='GOSERVshopbig_outside', blank=True, null=True)  # Field name made lowercase.
    goservshopbig_dnu = models.FloatField(db_column='GOSERVshopbig_dnu', blank=True, null=True)  # Field name made lowercase.
    goservrecent_local = models.FloatField(db_column='GOSERVrecent_local', blank=True, null=True)  # Field name made lowercase.
    goservrecent_outside = models.FloatField(db_column='GOSERVrecent_outside', blank=True, null=True)  # Field name made lowercase.
    goservrecent_dnu = models.FloatField(db_column='GOSERVrecent_dnu', blank=True, null=True)  # Field name made lowercase.
    goservchurch_local = models.FloatField(db_column='GOSERVchurch_local', blank=True, null=True)  # Field name made lowercase.
    goservchurch_outside = models.FloatField(db_column='GOSERVchurch_outside', blank=True, null=True)  # Field name made lowercase.
    goservchurch_dnu = models.FloatField(db_column='GOSERVchurch_dnu', blank=True, null=True)  # Field name made lowercase.
    novolnotime_sa = models.FloatField(db_column='NOVOLnotime_sa', blank=True, null=True)  # Field name made lowercase.
    novolnotime_a = models.FloatField(db_column='NOVOLnotime_a', blank=True, null=True)  # Field name made lowercase.
    novolnotime_n = models.FloatField(db_column='NOVOLnotime_n', blank=True, null=True)  # Field name made lowercase.
    novolnotime_d = models.FloatField(db_column='NOVOLnotime_d', blank=True, null=True)  # Field name made lowercase.
    novolnotime_sd = models.FloatField(db_column='NOVOLnotime_sd', blank=True, null=True)  # Field name made lowercase.
    novolnoskills_sa = models.FloatField(db_column='NOVOLnoskills_sa', blank=True, null=True)  # Field name made lowercase.
    novolnoskills_a = models.FloatField(db_column='NOVOLnoskills_a', blank=True, null=True)  # Field name made lowercase.
    novolnoskills_n = models.FloatField(db_column='NOVOLnoskills_n', blank=True, null=True)  # Field name made lowercase.
    novolnoskills_d = models.FloatField(db_column='NOVOLnoskills_d', blank=True, null=True)  # Field name made lowercase.
    novolnoskills_sd = models.FloatField(db_column='NOVOLnoskills_sd', blank=True, null=True)  # Field name made lowercase.
    novoldnkhow_sa = models.FloatField(db_column='NOVOLdnkhow_sa', blank=True, null=True)  # Field name made lowercase.
    novoldnkhow_a = models.FloatField(db_column='NOVOLdnkhow_a', blank=True, null=True)  # Field name made lowercase.
    novoldnkhow_n = models.FloatField(db_column='NOVOLdnkhow_n', blank=True, null=True)  # Field name made lowercase.
    novoldnkhow_d = models.FloatField(db_column='NOVOLdnkhow_d', blank=True, null=True)  # Field name made lowercase.
    novoldnkhow_sd = models.FloatField(db_column='NOVOLdnkhow_sd', blank=True, null=True)  # Field name made lowercase.
    novolhelprefused_sa = models.FloatField(db_column='NOVOLhelprefused_sa', blank=True, null=True)  # Field name made lowercase.
    novolhelprefused_a = models.FloatField(db_column='NOVOLhelprefused_a', blank=True, null=True)  # Field name made lowercase.
    novolhelprefused_n = models.FloatField(db_column='NOVOLhelprefused_n', blank=True, null=True)  # Field name made lowercase.
    novolhelprefused_d = models.FloatField(db_column='NOVOLhelprefused_d', blank=True, null=True)  # Field name made lowercase.
    novolhelprefused_sd = models.FloatField(db_column='NOVOLhelprefused_sd', blank=True, null=True)  # Field name made lowercase.
    novolnointerest_sa = models.FloatField(db_column='NOVOLnointerest_sa', blank=True, null=True)  # Field name made lowercase.
    novolnointerest_a = models.FloatField(db_column='NOVOLnointerest_a', blank=True, null=True)  # Field name made lowercase.
    novolnointerest_n = models.FloatField(db_column='NOVOLnointerest_n', blank=True, null=True)  # Field name made lowercase.
    novolnointerest_d = models.FloatField(db_column='NOVOLnointerest_d', blank=True, null=True)  # Field name made lowercase.
    novolnointerest_sd = models.FloatField(db_column='NOVOLnointerest_sd', blank=True, null=True)  # Field name made lowercase.
    novolnotasked_sa = models.FloatField(db_column='NOVOLnotasked_sa', blank=True, null=True)  # Field name made lowercase.
    novolnotasked_a = models.FloatField(db_column='NOVOLnotasked_a', blank=True, null=True)  # Field name made lowercase.
    novolnotasked_n = models.FloatField(db_column='NOVOLnotasked_n', blank=True, null=True)  # Field name made lowercase.
    novolnotasked_d = models.FloatField(db_column='NOVOLnotasked_d', blank=True, null=True)  # Field name made lowercase.
    novolnotasked_sd = models.FloatField(db_column='NOVOLnotasked_sd', blank=True, null=True)  # Field name made lowercase.
    novolnoproject_sa = models.FloatField(db_column='NOVOLnoproject_sa', blank=True, null=True)  # Field name made lowercase.
    novolnoproject_a = models.FloatField(db_column='NOVOLnoproject_a', blank=True, null=True)  # Field name made lowercase.
    novolnoproject_n = models.FloatField(db_column='NOVOLnoproject_n', blank=True, null=True)  # Field name made lowercase.
    novolnoproject_d = models.FloatField(db_column='NOVOLnoproject_d', blank=True, null=True)  # Field name made lowercase.
    novolnoproject_sd = models.FloatField(db_column='NOVOLnoproject_sd', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'soc1994'
